// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BankSystem.Models;
using Microsoft.EntityFrameworkCore;

namespace BankSystem.Context;

public partial class bankContext : DbContext
{
    public bankContext()
    {
    }

    public bankContext(DbContextOptions<bankContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tb_categorias> tb_categorias { get; set; }

    public virtual DbSet<tb_transacoes> tb_transacoes { get; set; }

    public virtual DbSet<tb_usuarios> tb_usuarios { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=bank_system;User ID=RAFA;Password=9173rafa");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tb_categorias>(entity =>
        {
            entity.HasKey(e => e.cat_id).HasName("PK_TB_CATEGORIAS");

            entity.Property(e => e.cat_id).ValueGeneratedNever();
        });

        modelBuilder.Entity<tb_transacoes>(entity =>
        {
            entity.HasKey(e => e.tra_id).HasName("PK_TB_TRANSACOES");

            entity.Property(e => e.tra_id).ValueGeneratedNever();

            entity.HasOne(d => d.tra_fk_categoria).WithMany(p => p.tb_transacoes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("tb_transacoes_fk0");

            entity.HasOne(d => d.tra_fk_usuario).WithMany(p => p.tb_transacoes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("tb_transacoes_fk1");
        });

        modelBuilder.Entity<tb_usuarios>(entity =>
        {
            entity.HasKey(e => e.usu_id).HasName("PK_TB_USUARIOS");

            entity.Property(e => e.usu_id).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}