// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankSystem.Models;

public partial class tb_categorias
{
    [Key]
    public int cat_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string cat_descricao { get; set; }

    [InverseProperty("tra_fk_categoria")]
    public virtual ICollection<tb_transacoes> tb_transacoes { get; set; } = new List<tb_transacoes>();
}