// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankSystem.Models;

public partial class tb_transacoes
{
    [Key]
    public int tra_id { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string tra_descricao { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal tra_valor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime tra_data { get; set; }

    public int tra_fk_categoria_id { get; set; }

    public int tra_fk_usuario_id { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string tra_tipo { get; set; }

    [ForeignKey("tra_fk_categoria_id")]
    [InverseProperty("tb_transacoes")]
    public virtual tb_categorias tra_fk_categoria { get; set; }

    [ForeignKey("tra_fk_usuario_id")]
    [InverseProperty("tb_transacoes")]
    public virtual tb_usuarios tra_fk_usuario { get; set; }
}