// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankSystem.Models;

//[Index("usu_email", Name = "UQ__tb_usuar__15C443D786EE29BD", IsUnique = true)]
public partial class tb_usuarios
{
    [Key]
    public int usu_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string usu_nome { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string usu_email { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string usu_senha { get; set; }

    [InverseProperty("tra_fk_usuario")]
    public virtual ICollection<tb_transacoes> tb_transacoes { get; set; } = new List<tb_transacoes>();
}